/**
 * Alle UI-Texte an einem Ort. Deutsch mit bewussten Anglizismen („on track“,
 * „Momentum“, „Trigger“). Keine Scham-Sprache: nie „versagt“, „clean“,
 * „Rückfall-Serie“ o. Ä. — neutral und faktisch.
 */
export const copy = {
  appName: 'bounceBack',
  tagline: 'Trend statt Streak.',

  tabs: {
    today: 'Heute',
    trend: 'Trend',
    history: 'Verlauf',
    more: 'Mehr',
  },

  common: {
    save: 'Speichern',
    cancel: 'Abbrechen',
    add: 'Hinzufügen',
    delete: 'Löschen',
    rename: 'Umbenennen',
    loading: 'Lädt…',
  },

  today: {
    onTrack: 'On track',
    notToday: 'Heute nicht',
    notYesterday: 'Gestern nicht',
    notOnTrack: 'Nicht on track',
    specialDay: 'Special Day',
    loggedSpecial: (day: string) => `Eingetragen: ${day} — Special Day`,
    targetToday: (day: string) => `Heute — ${day}`,
    targetYesterday: (day: string) => `Gestern — ${day}`,
    logged: (day: string, onTrack: boolean) =>
      `Eingetragen: ${day} — ${onTrack ? 'on track' : 'nicht on track'}`,
    change: 'Ändern',
    triggers: 'Trigger? (optional)',
    severityTitle: 'Wie stark? (optional)',
    severity: { 1: 'Leicht', 2: 'Mittel', 3: 'Deutlich' } as Record<1 | 2 | 3, string>,
    newTagPlaceholder: 'Neuer Trigger…',
    addTagChip: '+ Neu',
    notePlaceholder: 'Notiz (optional)',
    done: 'Fertig',
    tabRate: 'Gestern bewerten',
    tabJournal: 'Heute notieren',
    journalTitle: (day: string) => `Heute — ${day}`,
    journalHint:
      'Bewertet wird dieser Tag erst morgen. Was du jetzt festhältst, ist dann schon da.',
    journalTriggers: 'Was ist gerade los?',
    journalNotePlaceholder: 'Was du gerade denkst, fühlst, tust…',
    journalSaved: 'Gespeichert',
    carriedNote: (text: string) => `Damals notiert: „${text}“`,
    perfectWeeks: (n: number) => (n === 1 ? '1 perfekte Woche' : `${n} perfekte Wochen`),
    perfectWeekGoal: 'Alle sieben Tage on track = eine perfekte Woche.',
    weekTitle: 'Diese Woche',
    weekProgress: (n: number) => `${n} von 7`,
    weekNext: 'Nächste Woche neu',
    slipCost: (from: number, to: number) => `Ein Ausrutscher heute: Momentum ${from} → ${to}`,
    emptyTitle: 'Leg deinen ersten Habit an',
    emptyHint: 'Das, worum es gerade geht. Weitere kannst du später unter „Mehr“ hinzufügen.',
    modeHint: 'Aktives (Gym) trägst du am selben Tag ein — Lassen (z. B. Rauchen) erst am Folgetag, wenn der Tag rum ist.',
    habitNamePlaceholder: 'Name des Habits',
    start: 'Los geht’s',
    statLine: (pct: string, momentum: number) => `30 Tage: ${pct} · Momentum ${momentum}`,
  },

  trend: {
    headlinePct: 'der letzten 30 Tage on track',
    noData: 'Noch keine Einträge — ab dem ersten Log entsteht hier deine Kurve.',
    momentum: 'Momentum',
    momentumHint: 'Steigt langsam, sinkt bei einem Ausrutscher nur leicht — nie auf null.',
    momentumInfoLabel: 'Was ist Momentum?',
    momentumInfo:
      'Dein Ausdauerbalken. Er startet bei 50 und jeder On-track-Tag (auch Special Days) gibt +2. Ein „Nicht on track“-Tag zieht ab — je nach Stärke −6, −10 oder −14 — aber nie auf null: ein Ausrutscher ist ein Dip, kein Absturz. Ein deutlicher kostet dich damit genau eine Woche Aufbau. Tage ohne Eintrag ändern nichts. Kurz: Die 30-Tage-% zeigen deine Richtung, Momentum zeigt, wie viel Puffer du dir aufgebaut hast.',
    days: (n: number) => `${n} Tage`,
    patterns: 'Muster',
    patternsEmpty: 'Noch nicht genug Daten — Muster erscheinen nach ein paar Einträgen.',
    patternTags: 'Häufigste Trigger an „Nicht on track“-Tagen',
    patternWeekdays: 'Wochentage der „Nicht on track“-Tage',
    ofTotal: (n: number, total: number) => `${n} von ${total}`,
  },

  history: {
    legendOnTrack: 'on track',
    legendNot: 'nicht on track',
    legendSpecial: 'Special Day',
    legendNone: 'kein Eintrag',
    legendNote: 'Notiz',
    legendOpen: 'nur notiert',
    removeEntry: 'Eintrag entfernen',
    notRateableYet: 'Dieser Tag ist noch nicht vorbei — bewerten kannst du ihn morgen.',
  },

  more: {
    habits: 'Habits',
    addHabit: 'Neuer Habit…',
    logModeSame: 'Gleicher Tag',
    logModeNext: 'Folgetag',
    deleteHabitConfirm: (name: string) => `„${name}“ und alle zugehörigen Einträge löschen?`,
    habitDeleteOnlineOnly: 'Habits löschen geht nur mit Internetverbindung.',
    tags: 'Trigger-Tags',
    addTag: 'Neuer Trigger…',
    deleteTagConfirm: (label: string) => `Tag „${label}“ löschen? Bestehende Einträge behalten ihn.`,
    sync: 'Sync',
    syncLocal: 'Lokaler Modus — Supabase ist noch nicht verbunden. Anleitung: README.md',
    syncOffline: 'Offline — Änderungen werden später synchronisiert',
    syncSynced: 'Synchronisiert',
    syncSyncing: 'Synchronisiert…',
    syncError: 'Sync-Fehler — wird erneut versucht',
    syncNow: 'Jetzt synchronisieren',
    lastSync: (t: string) => `Zuletzt: ${t}`,
    account: 'Account',
    signOut: 'Abmelden',
    signOutUnsyncedError:
      'Es gibt noch ungesicherte Änderungen — erst synchronisieren, dann klappt das Abmelden (schützt davor, dass Daten verloren gehen).',
    exportCsv: 'CSV-Export',
    exportSoon: 'bald',
    appearance: 'Darstellung',
    themeSystem: 'System',
    themeLight: 'Hell',
    themeDark: 'Dunkel',
    reminder: 'Erinnerung',
    reminderHint: 'Eine sanfte Nachricht am Abend — kein Streak-Gemecker, nur ein kurzes „Wie war gestern?“.',
    reminderUnsupported:
      'Auf dem iPhone zuerst „Zum Home-Bildschirm hinzufügen“ — Mitteilungen gehen nur in der installierten App (iOS 16.4+).',
    reminderEnable: 'Aktivieren',
    reminderDisable: 'Deaktivieren',
    reminderDenied:
      'Mitteilungen sind blockiert — in den System-Einstellungen für bounceBack erlauben und nochmal versuchen.',
    reminderActive: (hour: number) => `Aktiv — täglich gegen ${hour}:00 Uhr`,
    reminderTime: 'Uhrzeit',
  },

  onboarding: {
    skip: 'Überspringen',
    next: 'Weiter',
    start: 'Los geht’s',
    step1Title: 'Trend statt Streak.',
    step1Body:
      'Kein Zähler, der bei einem Ausrutscher auf null springt: Du siehst deine Richtung über die letzten 30 Tage. Ein schlechter Tag ist ein Dip — kein Absturz.',
    step2Title: 'Bewertet wird der Tag, der vorbei ist.',
    step2Body:
      'Beispiel Rauchen: Du trägst heute ein, wie gestern lief — um 14 Uhr weißt du ja noch nicht, wie der Abend wird. Aktives wie Gym trägst du dagegen am selben Tag ein.',
    step3Title: 'Trigger zeigen dir Muster.',
    step3Body:
      'Lief ein Tag nicht, tippst du optional an, was los war — nach ein paar Einträgen zeigt dir die App deine Muster. Richtig gute Tage markierst du blau als Special Day.',
  },

  auth: {
    signIn: 'Anmelden',
    signUp: 'Konto erstellen',
    email: 'E-Mail',
    password: 'Passwort (mind. 6 Zeichen)',
    switchToSignUp: 'Neu hier? Konto erstellen',
    switchToSignIn: 'Schon ein Konto? Anmelden',
    confirmSentTitle: 'Bestätigungs-Mail geschickt',
    confirmSentBody: (email: string) =>
      `Wir haben eine Mail an ${email} geschickt — auch im Spam-Ordner nachsehen. Nach dem Bestätigen hier anmelden.`,
    backToSignIn: 'Zur Anmeldung',
    forgotLink: 'Passwort vergessen?',
    forgotTitle: 'Passwort zurücksetzen',
    forgotBody: 'Wir schicken dir einen Link, mit dem du ein neues Passwort setzen kannst.',
    forgotSubmit: 'Link schicken',
    forgotSentTitle: 'Link ist unterwegs',
    forgotSentBody: (email: string) =>
      `Falls es ein Konto zu ${email} gibt, liegt gleich eine Mail im Postfach — auch im Spam nachsehen.`,
    newPasswordTitle: 'Neues Passwort setzen',
    newPasswordPlaceholder: 'Neues Passwort (mind. 6 Zeichen)',
    newPasswordSubmit: 'Passwort speichern',
    errors: {
      invalid: 'E-Mail oder Passwort falsch',
      notConfirmed: 'E-Mail noch nicht bestätigt — sieh in dein Postfach (auch Spam)',
      weakPassword: 'Passwort zu kurz — mindestens 6 Zeichen',
      generic: 'Hat nicht geklappt — bitte nochmal versuchen',
    },
  },
} as const
